language: android
jdk: oraclejdk8
sudo: false

cache:
  directories:
  - $HOME/.gradle/caches/2.14.1
  - $HOME/.gradle/caches/jars-1
  - $HOME/.gradle/daemon
  - $HOME/.gradle/native
  - $HOME/.gradle/wrapper

branches:
  only:
  - master
  - develop
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.1
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-25
  - sys-img-armeabi-v7a-android-25
  - sys-img-x86-android-25
script:
- ./gradlew testfairyDebug

notifications:
  slack: pickmeup-bsf:NQfFpQo96qClEKvbjvy0lGly
