language: android
jdk: oraclejdk8
sudo: false
branches:
  only:
  - master
  - develop
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.1
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-25
  - sys-img-armeabi-v7a-android-25
  - sys-img-x86-android-25
script:
- ./gradlew assembleDebug

notifications:
  slack: pickmeup-bsf:NQfFpQo96qClEKvbjvy0lGly