language: android

sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.13
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

branches:
  only:
    - master

android:
  components:

    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23


    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23
    - sys-img-x86-android-23

script:
      - ./gradlew assembleQa -PdisablePreDex


