language: android
sudo: false
cache:
  directories:
  - $HOME/.gradle/caches/2.14.1
  - $HOME/.gradle/caches/jars-1
  - $HOME/.gradle/daemon
  - $HOME/.gradle/native
  - $HOME/.gradle/wrapper
branches:
  only:
  - master
  - develop
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-23
  - sys-img-armeabi-v7a-android-23
  - sys-img-x86-android-23
script:
- ./gradlew assembleDebug

notifications:
  slack: pickmeup-bsf:NQfFpQo96qClEKvbjvy0lGly
